import {defineStore} from 'pinia'
import {ref} from 'vue'
import {merchantApi,merchantDemoMode,merchantSession} from '../api/client'

export interface MerchantSummary{available:string;reserved:string;pending:string;physicalLiquidity:'Healthy'|'Limited'|'Unavailable'}
export interface PortalTransaction{id:string;reference:string;kind:'deposit'|'withdrawal';customer_id:string;customer_phone:string;amount:string;credited_amount:string|null;status:string;p2p_status:string;created_at:string}
export interface PortalIdentity{user:{id:string;email:string;display_name:string;role:'owner'|'admin'|'support'};merchant:{id:string;slug:string;name:string}}
export interface PortalApiKey{id:string;environment:'test'|'live';label:string;prefix:string;active:boolean;created_at:string;last_used_at:string|null;revoked_at:string|null}
export interface PortalWebhook{id:string;url:string;enabled:boolean;created_at:string;deliveries:Array<{id:string;event_id:string;event_type:string;status:string;attempt:number;response_code:number|null;created_at:string;delivered_at:string|null}>}
export interface PortalSettlement{id:string;reference:string;amount:string;currency:'ETB';destination_phone_masked:string;expected_name:string;status:string;requested_at:string;reviewed_at:string|null}
export interface PortalSettingChange{id:string;scope_type:'merchant';scope_id:string;version:number;proposed:Record<string,unknown>;status:'pending'|'approved'|'rejected';proposed_by:string;reviewed_by:string|null;review_reason:string|null;reviewed_at:string|null;created_at:string}
export interface MerchantPolicy{allow_alternate_withdrawal_phone:boolean;deposit_minimum:string;deposit_maximum:string;wrong_amount_tolerance:string;reserve_provider_fee:string;gateway_fee_flat:string;deposit_countdown_seconds:number;deposit_late_grace_seconds:number;technical_difficulty_message:string}
export interface MerchantTeamMember{id:string;email:string;display_name:string;role:'owner'|'admin'|'support';status:string;last_login_at:string|null}
export interface MerchantInvitation{id:string;email:string;role:'owner'|'admin'|'support';expires_at:string}
export type SupportCaseStatus='open'|'investigating'|'awaiting_merchant'|'resolved'|'closed'
export type SupportCaseCategory='transaction_match'|'withdrawal_outcome'|'topup'|'settlement'|'webhook'|'api'|'other'
export interface SupportProposedMatch{kind:'deposit_intent'|'incoming_receipt'|'withdrawal'|'provider_transaction';reference:string;explanation?:string}
export interface PortalSupportMessage{id:string;body:string;evidence_reference:string|null;proposed_match:SupportProposedMatch|null;author:{type:'merchant_user'|'platform_staff'|'former_user';id:string|null;display_name:string};created_at:string}
export interface PortalSupportCase{id:string;environment:'test'|'live';category:SupportCaseCategory;subject:string;reference:string|null;status:SupportCaseStatus;workflow_note:string|null;created_by:{id:string;display_name:string}|null;assigned_to:{id:string;display_name:string}|null;message_count:number;messages?:PortalSupportMessage[];created_at:string;updated_at:string;resolved_at:string|null;financial_resolution_performed:false}
export const useMerchantStore=defineStore('merchant',()=>{
  const environment=ref<'test'|'live'>('live')
  const summary=ref<MerchantSummary>(merchantDemoMode?{available:'4,182,640.25',reserved:'72,450.00',pending:'18,200.00',physicalLiquidity:'Healthy'}:{available:'0.00',reserved:'0.00',pending:'0.00',physicalLiquidity:'Unavailable'})
  const identity=ref<PortalIdentity|null>(merchantDemoMode?{user:{id:'demo',email:'owner@example.test',display_name:'Abel Mekonnen',role:'owner'},merchant:{id:'demo',slug:'asterbet',name:'AsterBet'}}:null)
  const transactions=ref<PortalTransaction[]>([])
  const apiKeys=ref<PortalApiKey[]>(merchantDemoMode?[{id:'demo-key',environment:'live',label:'Production server',prefix:'sk_live_demo11a2',active:true,created_at:'2026-07-02T00:00:00Z',last_used_at:new Date().toISOString(),revoked_at:null}]:[])
  const webhooks=ref<PortalWebhook[]>(merchantDemoMode?[{id:'demo-hook',url:'https://merchant.example/webhooks/orbitpay',enabled:true,created_at:'2026-07-02T00:00:00Z',deliveries:[{id:'demo-delivery',event_id:'evt_demo201',event_type:'transaction.success',status:'delivered',attempt:1,response_code:200,created_at:new Date().toISOString(),delivered_at:new Date().toISOString()}]}]:[])
  const settlements=ref<PortalSettlement[]>([])
  const settingChanges=ref<PortalSettingChange[]>(merchantDemoMode?[{id:'demo-setting',scope_type:'merchant',scope_id:'demo',version:3,proposed:{allow_alternate_withdrawal_phone:false,deposit_minimum:'10.00',deposit_maximum:'50000.00',wrong_amount_tolerance:'1.00',reserve_provider_fee:'25.00',gateway_fee_flat:'0.00',deposit_countdown_seconds:600,deposit_late_grace_seconds:1800,technical_difficulty_message:'We cannot process this request right now. Please try again shortly.'},status:'approved',proposed_by:'demo',reviewed_by:'platform-demo',review_reason:'Demo approved policy',reviewed_at:new Date().toISOString(),created_at:new Date().toISOString()}]:[])
  const activePolicy=ref<MerchantPolicy>(merchantDemoMode?settingChanges.value[0].proposed as unknown as MerchantPolicy:{allow_alternate_withdrawal_phone:false,deposit_minimum:'10.00',deposit_maximum:'50000.00',wrong_amount_tolerance:'1.00',reserve_provider_fee:'25.00',gateway_fee_flat:'0.00',deposit_countdown_seconds:600,deposit_late_grace_seconds:1800,technical_difficulty_message:'We cannot process this request right now. Please try again shortly.'})
  const team=ref<MerchantTeamMember[]>(merchantDemoMode?[{id:'demo',email:'owner@example.test',display_name:'Abel Mekonnen',role:'owner',status:'active',last_login_at:new Date().toISOString()}]:[])
  const invitations=ref<MerchantInvitation[]>([])
  const supportCases=ref<PortalSupportCase[]>(merchantDemoMode?[{id:'demo-support-1',environment:'live',category:'withdrawal_outcome',subject:'Unknown withdrawal outcome',reference:'WD-38204',status:'investigating',workflow_note:'Provider evidence is being reviewed.',created_by:{id:'demo',display_name:'Abel Mekonnen'},assigned_to:{id:'platform-demo',display_name:'OrbitPay Support'},message_count:3,messages:[{id:'demo-message-1',body:'This transfer reached the provider confirmation boundary. It has not been retried and platform operations is reconciling the result.',evidence_reference:null,proposed_match:null,author:{type:'platform_staff',id:'platform-demo',display_name:'OrbitPay Support'},created_at:new Date(Date.now()-12*60_000).toISOString()},{id:'demo-message-2',body:'The customer says the funds have not arrived. Their Telebirr message is attached as secure evidence.',evidence_reference:'evidence://merchant/customer-sms-38204',proposed_match:null,author:{type:'merchant_user',id:'demo',display_name:'Abel Mekonnen'},created_at:new Date(Date.now()-8*60_000).toISOString()},{id:'demo-message-3',body:'Thank you. We are checking the sending wallet balance and provider transaction history. No customer action is required yet.',evidence_reference:null,proposed_match:null,author:{type:'platform_staff',id:'platform-demo',display_name:'OrbitPay Support'},created_at:new Date(Date.now()-4*60_000).toISOString()}],created_at:new Date(Date.now()-15*60_000).toISOString(),updated_at:new Date(Date.now()-4*60_000).toISOString(),resolved_at:null,financial_resolution_performed:false}]:[])
  const loading=ref(false)
  const authError=ref('')
  const lastUpdated=ref(new Date())
  const authenticated=ref(merchantDemoMode||Boolean(merchantSession.get()))
  async function login(email:string,password:string,merchantSlug?:string){authError.value='';loading.value=true;try{const result=await merchantApi<{session_token:string;user:PortalIdentity['user'];merchant:PortalIdentity['merchant']}>('/portal/auth/login',{method:'POST',body:JSON.stringify({email,password,merchant_slug:merchantSlug||undefined})});merchantSession.set(result.session_token);authenticated.value=true;identity.value={user:result.user,merchant:result.merchant};await refresh()}catch(error){authError.value=error instanceof Error?error.message:'Sign in failed';throw error}finally{loading.value=false}}
  async function restore(){if(merchantDemoMode)return;if(!merchantSession.get()){authenticated.value=false;return}try{identity.value=await merchantApi<PortalIdentity>('/portal/auth/me');authenticated.value=true;await refresh()}catch{merchantSession.clear();authenticated.value=false;identity.value=null}}
  async function logout(){try{if(!merchantDemoMode)await merchantApi('/portal/auth/logout',{method:'POST'})}finally{merchantSession.clear();authenticated.value=merchantDemoMode;identity.value=merchantDemoMode?identity.value:null}}
  async function loadSummary(){if(merchantDemoMode){lastUpdated.value=new Date();return}const result=await merchantApi<{available:string;reserved:string;pending:string;physical_liquidity:MerchantSummary['physicalLiquidity'];updated_at:string}>(`/portal/summary?environment=${environment.value}`);summary.value={available:result.available,reserved:result.reserved,pending:result.pending,physicalLiquidity:result.physical_liquidity};lastUpdated.value=new Date(result.updated_at)}
  async function loadTransactions(){if(merchantDemoMode)return;transactions.value=await merchantApi<PortalTransaction[]>(`/portal/transactions?environment=${environment.value}&limit=100`)}
  async function loadDeveloper(){if(merchantDemoMode)return;[apiKeys.value,webhooks.value]=await Promise.all([merchantApi<PortalApiKey[]>(`/portal/api-keys?environment=${environment.value}`),merchantApi<PortalWebhook[]>(`/portal/webhook-logs?environment=${environment.value}`)])}
  async function createApiKey(label:string){const result=await merchantApi<PortalApiKey&{secret_key:string}>('/portal/api-keys',{method:'POST',body:JSON.stringify({environment:environment.value,label})});await loadDeveloper();return result}
  async function revokeApiKey(id:string){await merchantApi(`/portal/api-keys/${id}`,{method:'DELETE'});await loadDeveloper()}
  async function createWebhook(url:string){const result=await merchantApi<{id:string;secret:string}>(`/portal/webhook-endpoints`,{method:'POST',body:JSON.stringify({environment:environment.value,url})});await loadDeveloper();return result}
  async function setWebhookEnabled(id:string,enabled:boolean){if(merchantDemoMode){const endpoint=webhooks.value.find(item=>item.id===id);if(endpoint)endpoint.enabled=enabled;return}await merchantApi(`/portal/webhook-endpoints/${id}`,{method:'PATCH',body:JSON.stringify({environment:environment.value,enabled})});await loadDeveloper()}
  async function rotateWebhookSecret(id:string){if(merchantDemoMode)return{secret:'whsec_demo_rotated_secret'};const result=await merchantApi<{secret:string}>(`/portal/webhook-endpoints/${id}/rotate-secret`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({environment:environment.value})});await loadDeveloper();return result}
  async function replayWebhook(id:string){await merchantApi(`/portal/webhook-deliveries/${id}/replay?environment=${environment.value}`,{method:'POST'});await loadDeveloper()}
  async function loadSettlements(){if(merchantDemoMode)return;settlements.value=await merchantApi<PortalSettlement[]>(`/portal/settlements?environment=${environment.value}`)}
  async function createSettlement(input:{reference:string;account_number:string;expected_name:string;amount:string;metadata?:Record<string,unknown>}){const result=await merchantApi<PortalSettlement>(`/portal/settlements?environment=${environment.value}`,{method:'POST',body:JSON.stringify({...input,currency:'ETB'})});await loadSettlements();return result}
  async function createTopup(input:{tx_ref:string;amount:string;first_name:string;phone_number:string}){return merchantApi<{checkout_url:string;tx_ref:string;receiver_name:string}>(`/portal/topups?environment=${environment.value}`,{method:'POST',body:JSON.stringify({...input,currency:'ETB',customer_id:`portal-topup-${Date.now()}`})})}
  async function loadSettingChanges(){if(merchantDemoMode)return;[settingChanges.value,activePolicy.value]=await Promise.all([merchantApi<PortalSettingChange[]>('/portal/settings/changes'),merchantApi<MerchantPolicy>('/portal/settings/current')])}
  async function proposeSettings(proposed:Record<string,unknown>,reason:string){const result=await merchantApi<PortalSettingChange>('/portal/settings/changes',{method:'POST',body:JSON.stringify({proposed,reason})});await loadSettingChanges();return result}
  async function loadTeam(){if(merchantDemoMode)return;const result=await merchantApi<{users:MerchantTeamMember[];pending_invitations:MerchantInvitation[]}>('/portal/users');team.value=result.users;invitations.value=result.pending_invitations}
  async function inviteUser(email:string,role:'admin'|'support'){const result=await merchantApi<MerchantInvitation&{invitation_token:string}>('/portal/invitations',{method:'POST',body:JSON.stringify({email,role})});await loadTeam();return result}
  async function loadSupportCases(){if(merchantDemoMode)return;supportCases.value=await merchantApi<PortalSupportCase[]>(`/portal/support/cases?environment=${environment.value}&limit=100`)}
  async function loadSupportCase(id:string){if(merchantDemoMode)return supportCases.value.find(item=>item.id===id)??null;const detail=await merchantApi<PortalSupportCase>(`/portal/support/cases/${id}`);const index=supportCases.value.findIndex(item=>item.id===id);if(index>=0)supportCases.value[index]=detail;else supportCases.value.unshift(detail);return detail}
  async function createSupportCase(input:{category:SupportCaseCategory;subject:string;reference?:string;message:string;evidence_reference?:string;proposed_match?:SupportProposedMatch}){if(merchantDemoMode){const created:PortalSupportCase={id:`demo-support-${Date.now()}`,environment:environment.value,category:input.category,subject:input.subject,reference:input.reference||null,status:'open',workflow_note:null,created_by:identity.value?{id:identity.value.user.id,display_name:identity.value.user.display_name}:null,assigned_to:null,message_count:1,messages:[{id:`demo-message-${Date.now()}`,body:input.message,evidence_reference:input.evidence_reference||null,proposed_match:input.proposed_match||null,author:{type:'merchant_user',id:identity.value?.user.id??null,display_name:identity.value?.user.display_name??'You'},created_at:new Date().toISOString()}],created_at:new Date().toISOString(),updated_at:new Date().toISOString(),resolved_at:null,financial_resolution_performed:false};supportCases.value.unshift(created);return created}const result=await merchantApi<PortalSupportCase>('/portal/support/cases',{method:'POST',body:JSON.stringify({...input,environment:environment.value})});supportCases.value.unshift(result);return result}
  async function addSupportMessage(id:string,input:{message:string;evidence_reference?:string;proposed_match?:SupportProposedMatch}){if(merchantDemoMode){const item=supportCases.value.find(entry=>entry.id===id);if(!item)return null;const message:PortalSupportMessage={id:`demo-message-${Date.now()}`,body:input.message,evidence_reference:input.evidence_reference||null,proposed_match:input.proposed_match||null,author:{type:'merchant_user',id:identity.value?.user.id??null,display_name:identity.value?.user.display_name??'You'},created_at:new Date().toISOString()};item.messages=[...(item.messages??[]),message];item.message_count=item.messages.length;item.updated_at=message.created_at;return item}const result=await merchantApi<PortalSupportCase>(`/portal/support/cases/${id}/messages`,{method:'POST',body:JSON.stringify(input)});const index=supportCases.value.findIndex(item=>item.id===id);if(index>=0)supportCases.value[index]=result;return result}
  async function refresh(){loading.value=true;try{await Promise.all([loadSummary(),loadTransactions()])}finally{loading.value=false}}
  async function switchEnvironment(value:'test'|'live'){environment.value=value;if(authenticated.value)await refresh()}
  return{environment,summary,identity,transactions,apiKeys,webhooks,settlements,settingChanges,activePolicy,team,invitations,supportCases,loading,authError,lastUpdated,authenticated,demoMode:merchantDemoMode,login,restore,logout,refresh,loadTransactions,loadDeveloper,createApiKey,revokeApiKey,createWebhook,setWebhookEnabled,rotateWebhookSecret,replayWebhook,loadSettlements,createSettlement,createTopup,loadSettingChanges,proposeSettings,loadTeam,inviteUser,loadSupportCases,loadSupportCase,createSupportCase,addSupportMessage,switchEnvironment}
})
