<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Check, Clock, Document, Refresh, Warning } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import StatusPill from '../components/StatusPill.vue'
import { usePlatformStore } from '../stores/platform'

const platform=usePlatformStore(),selected=ref(''),dialog=ref(false),loading=ref(false)
const action=ref<'cancel'|'name_retry'|'success'|'failed'>('cancel'),reason=ref(''),password=ref(''),nameConfirmation=ref('')
const providerTransactionId=ref(''),resolvedName=ref(''),serviceFee=ref('0.00'),vat=ref('0.00'),currentBalance=ref(''),failureEvidence=ref('')
const cases=computed(()=>platform.reconciliationCases as any[]);const current=computed(()=>cases.value.find(item=>item.id===selected.value)??cases.value[0]??null)
const displayAmount=computed(()=>current.value?.transfer?`ETB ${current.value.transfer.amount}`:current.value?.receipt?.amount?`ETB ${current.value.receipt.amount}`:'—')
const canCancel=computed(()=>current.value?.transfer&&['accepted','queued','device_assigned'].includes(current.value.transfer.status))
const canNameRetry=computed(()=>current.value?.type==='receiver_name_review'&&current.value?.transfer?.status==='manual_review'&&!current.value.transfer.committed_at)
const canResolve=computed(()=>current.value?.transfer&&['unknown','manual_review'].includes(current.value.transfer.status)&&current.value?.type!=='receiver_name_review')
async function load(){loading.value=true;try{await platform.loadCases();if(!selected.value&&cases.value[0])selected.value=cases.value[0].id}finally{loading.value=false}}
onMounted(load)
function open(value:typeof action.value){action.value=value;reason.value='';password.value='';nameConfirmation.value='';providerTransactionId.value='';resolvedName.value='';serviceFee.value='0.00';vat.value='0.00';currentBalance.value='';failureEvidence.value='';dialog.value=true}
async function submit(){const transfer=current.value?.transfer;if(!transfer)return;if(action.value==='name_retry'&&nameConfirmation.value.trim()!==String(current.value?.evidence?.observed_name??'').trim()){ElMessage.error('Type the exact provider-observed name to approve it');return}loading.value=true;try{if(action.value==='cancel')await platform.cancelTransfer(transfer.id,reason.value,password.value);else if(action.value==='name_retry')await platform.approveNameRetry(transfer.id,reason.value,password.value);else await platform.resolveTransfer(transfer.id,{outcome:action.value,provider_transaction_id:action.value==='success'?providerTransactionId.value:undefined,resolved_name:action.value==='success'?(resolvedName.value||undefined):undefined,service_fee:action.value==='success'?serviceFee.value:undefined,vat:action.value==='success'?vat.value:undefined,current_main_balance:action.value==='success'&&currentBalance.value?currentBalance.value:undefined,failure_evidence_reference:action.value==='failed'?failureEvidence.value:undefined,reason:reason.value},password.value);dialog.value=false;ElMessage.success('Audited action completed');await load()}catch(error){ElMessage.error(error instanceof Error?error.message:'Action failed')}finally{loading.value=false}}
</script>
<template><div class="page"><div class="page-heading"><div><p class="eyebrow">Exception control</p><h1>Reconciliation</h1><span class="muted">Joined transfer, device, attempt and receipt evidence from the authoritative database.</span></div><div class="toolbar"><div class="safety"><el-icon><Check/></el-icon>No automated retry after PIN</div><el-button :icon="Refresh" :loading="loading" @click="load">Refresh</el-button></div></div>
<div class="recon-grid"><section class="panel case-list"><div class="panel-head"><div><h2>Cases</h2><span class="muted small">{{cases.length}} loaded</span></div></div><button v-for="item in cases" :key="item.id" :class="{active:selected===item.id}" @click="selected=item.id"><span :class="['risk',item.type==='unknown_payout'?'high':item.type==='receiver_name_review'?'medium':'low']"/><span class="case-main"><strong>{{String(item.type).replace(/_/g,' ')}}</strong><small>{{item.transfer?.reference??item.receipt?.provider_transaction_id??item.reference_id}} · {{item.transfer?.merchant?.name??item.merchant_id??'Unassigned'}}</small></span><span class="case-right"><b>{{item.transfer?`ETB ${item.transfer.amount}`:item.receipt?.amount?`ETB ${item.receipt.amount}`:'—'}}</b><small>{{new Date(item.created_at).toLocaleString()}}</small></span></button><el-empty v-if="!cases.length" description="No reconciliation cases"/></section>
<section class="panel evidence"><template v-if="current"><div class="panel-head"><div><p class="eyebrow">{{String(current.type).replace(/_/g,' ')}}</p><h2>{{current.transfer?.reference??current.receipt?.provider_transaction_id??current.reference_id}} · {{displayAmount}}</h2><span class="muted small">{{current.transfer?.merchant?.name??current.merchant_id??'Unassigned'}} · {{new Date(current.created_at).toLocaleString()}}</span></div><StatusPill :status="current.transfer?.status??current.status"/></div><div class="evidence-body"><div v-if="current.transfer?.committed_at" class="warning-banner"><el-icon><Warning/></el-icon><div><strong>PIN/commit boundary crossed</strong><span>Replacement transfer is prohibited until provider outcome is conclusively resolved.</span></div></div><div v-else-if="current.transfer" class="safe-banner"><el-icon><Check/></el-icon><div><strong>Pre-commit state</strong><span>Cancellation is allowed only while the device has not started. Name retry creates one new fenced attempt.</span></div></div>
<div v-if="current.transfer" class="evidence-cards"><article><el-icon><Document/></el-icon><div><span>Expected receiver</span><strong>{{current.transfer.expected_name}} · {{current.transfer.destination_phone_masked}}</strong></div></article><article><el-icon><Document/></el-icon><div><span>Provider-observed name</span><strong>{{current.evidence?.observed_name??current.transfer.resolved_name??'Not captured'}}</strong></div></article><article><el-icon><Document/></el-icon><div><span>Assigned wallet</span><strong>{{current.transfer.sim?`${current.transfer.sim.device_name} · SIM ${current.transfer.sim.slot+1}`:'Not assigned'}}</strong></div></article><article><el-icon><Document/></el-icon><div><span>Provider transaction</span><strong>{{current.transfer.provider_transaction_id??'Missing'}}</strong></div></article><article><el-icon><Document/></el-icon><div><span>Wallet balance evidence</span><strong>{{current.transfer.sim?`ETB ${current.transfer.sim.main_balance} · ${current.transfer.sim.last_balance_at?new Date(current.transfer.sim.last_balance_at).toLocaleString():'stale'}`:'Unavailable'}}</strong></div></article><article><el-icon><Document/></el-icon><div><span>Case evidence</span><strong>{{current.evidence?.reason??current.evidence?.error_code??'Structured evidence below'}}</strong></div></article></div>
<div v-if="current.transfer?.attempts?.length" class="timeline"><div v-for="attempt in current.transfer.attempts" :key="attempt.attempt_number" :class="attempt.committed_at?'pending':'done'"><i><Clock/></i><span><strong>Attempt {{attempt.attempt_number}} · {{attempt.job?.state??attempt.outcome??'created'}}</strong><small>{{attempt.job?.error_code??attempt.error_code??'No error'}}<template v-if="attempt.job?.last_screen_text"> · last screen retained</template></small></span></div></div>
<div v-if="current.receipt" class="evidence-cards"><article><el-icon><Document/></el-icon><div><span>Receipt</span><strong>{{current.receipt.provider_transaction_id??'No provider ID'}} · {{current.receipt.type}}</strong></div></article><article><el-icon><Document/></el-icon><div><span>Counterparty</span><strong>{{current.receipt.counterparty_name??'Unknown'}} · ***{{current.receipt.counterparty_phone_suffix??'—'}}</strong></div></article><article><el-icon><Document/></el-icon><div><span>Source wallet</span><strong>{{current.receipt.sim.device_name}} · SIM {{current.receipt.sim.slot+1}}</strong></div></article></div>
<details><summary>Structured evidence</summary><pre>{{JSON.stringify({evidence:current.evidence,proposal:current.proposal,resolution:current.resolution},null,2)}}</pre></details><div v-if="current.transfer" class="resolution-actions"><el-button v-if="canCancel" type="danger" plain @click="open('cancel')">Cancel pre-commit transfer</el-button><el-button v-if="canNameRetry" type="warning" @click="open('name_retry')">Approve exact name & retry</el-button><el-button v-if="canResolve" type="success" @click="open('success')">Resolve as succeeded</el-button><el-button v-if="canResolve" type="danger" @click="open('failed')">Resolve as failed</el-button></div></div></template><el-empty v-else description="Select a case"/></section></div>
<el-dialog v-model="dialog" :title="action==='cancel'?'Cancel pre-commit transfer':action==='name_retry'?'Approve exact provider name and retry':action==='success'?'Resolve unknown transfer as succeeded':'Resolve unknown transfer as failed'" width="min(590px,94vw)"><el-alert title="Your password is rechecked and the one-time authorization is consumed by this action." type="warning" :closable="false" show-icon/><el-form label-position="top" style="margin-top:16px"><el-form-item v-if="action==='name_retry'" :label="`Type exact observed name: ${current?.evidence?.observed_name??'missing'}`"><el-input v-model="nameConfirmation"/></el-form-item><template v-if="action==='success'"><el-form-item label="Provider transaction ID"><el-input v-model="providerTransactionId"/></el-form-item><el-form-item label="Resolved receiver name (optional)"><el-input v-model="resolvedName"/></el-form-item><div class="fee-grid"><el-form-item label="Service fee (ETB)"><el-input v-model="serviceFee" inputmode="decimal"/></el-form-item><el-form-item label="VAT (ETB)"><el-input v-model="vat" inputmode="decimal"/></el-form-item></div><el-form-item label="Current main balance from evidence (optional)"><el-input v-model="currentBalance" inputmode="decimal"/></el-form-item></template><el-form-item v-if="action==='failed'" label="Conclusive provider failure evidence reference"><el-input v-model="failureEvidence" placeholder="Receipt object key, provider case ID, or signed balance proof"/></el-form-item><el-form-item label="Audited reason"><el-input v-model="reason" type="textarea" :rows="3"/></el-form-item><el-form-item label="Your password"><el-input v-model="password" type="password" show-password autocomplete="current-password"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">Cancel</el-button><el-button :type="action==='failed'||action==='cancel'?'danger':'primary'" :loading="loading" @click="submit">Confirm audited action</el-button></template></el-dialog></div></template>
<style scoped>.safety{display:flex;align-items:center;gap:7px;padding:9px 12px;background:#e8f7f3;border-radius:9px;color:#087d69;font-size:11px;font-weight:700}.recon-grid{display:grid;grid-template-columns:minmax(300px,.8fr) minmax(540px,1.7fr);gap:18px}.case-list>button{width:100%;display:grid;grid-template-columns:6px 1fr auto;align-items:center;gap:12px;padding:16px 18px;border:0;border-top:1px solid var(--line);background:#fff;text-align:left;cursor:pointer}.case-list>button.active{background:#f5f5ff}.risk{width:5px;height:38px;border-radius:4px;background:#aaa}.risk.high{background:var(--danger)}.risk.medium{background:var(--amber)}.risk.low{background:var(--primary)}.case-main strong,.case-main small,.case-right b,.case-right small{display:block}.case-main strong{text-transform:capitalize;font-size:12px}.case-main small,.case-right small{font-size:10px;color:var(--muted);margin-top:4px}.case-right{text-align:right}.case-right b{font-size:11px}.evidence-body{padding:0 22px 24px}.warning-banner,.safe-banner{display:flex;gap:12px;padding:13px;border-radius:10px;margin-bottom:16px}.warning-banner{background:#fff3df;color:#9c5e0b}.safe-banner{background:#e8f7f3;color:#087d69}.warning-banner .el-icon,.safe-banner .el-icon{font-size:20px}.warning-banner strong,.warning-banner span,.safe-banner strong,.safe-banner span{display:block}.warning-banner span,.safe-banner span{font-size:10px;margin-top:3px}.evidence-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.evidence-cards article{padding:13px;border:1px solid var(--line);border-radius:9px;display:flex;gap:8px}.evidence-cards .el-icon{color:var(--primary)}.evidence-cards span,.evidence-cards strong{display:block}.evidence-cards span{font-size:9px;color:var(--muted);text-transform:uppercase}.evidence-cards strong{font-size:10px;margin-top:5px;line-height:1.35}.timeline{padding:18px 8px}.timeline>div{display:flex;gap:12px;min-height:48px}.timeline i{width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#e8f7f3;color:var(--teal);font-style:normal}.timeline strong,.timeline small{display:block}.timeline strong{font-size:11px;margin-top:4px}.timeline small{font-size:10px;color:var(--muted);margin-top:4px}details{margin-top:18px}summary{cursor:pointer;color:var(--primary);font-size:11px;font-weight:700}pre{padding:12px;background:#151b2b;color:#dbe1ee;border-radius:9px;max-height:260px;overflow:auto;font-size:10px}.resolution-actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap;margin-top:18px;border-top:1px solid var(--line);padding-top:16px}.fee-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:950px){.recon-grid{grid-template-columns:1fr}.evidence-cards{grid-template-columns:1fr}} </style>
