<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api, passwordReauthenticate, sensitiveApi } from '../api/client'
import { usePlatformStore } from '../stores/platform'

const platform=usePlatformStore(),active=ref('limits'),loading=ref(false),dialog=ref(false),password=ref(''),reason=ref('')
const action=ref<'draft'|'approve'|'reject'|'telegram'>('draft'),selected=ref('')
const settings=reactive({daily:150000,ceiling:75000,safety:5000,headroom:1000,stale:30,countdown:10,late:30,factor:70})
const telegram=reactive({chat:'',offline:true,unknown:true,balance:true,webhook:true})
const changes=ref<Array<{id:string;scope_type:string;scope_id:string;version:number;status:string;proposed:Record<string,unknown>;proposed_by:string;reviewed_by:string|null;created_at:string}>>([])
const pending=computed(()=>changes.value.filter(item=>item.status==='pending'))

async function load(){if(platform.demoMode)return;loading.value=true;try{const [rows,alerts]=await Promise.all([api<typeof changes.value>('/admin/configuration/changes'),api<{chat_id:string;enabled_types:string[]}>('/admin/alerts')]);changes.value=rows;telegram.chat=alerts.chat_id;const enabled=alerts.enabled_types;const all=enabled.includes('*');telegram.offline=all||enabled.includes('device_offline');telegram.unknown=all||enabled.includes('unknown_payout');telegram.balance=all||enabled.includes('stale_balance');telegram.webhook=all||enabled.includes('webhook_backlog');const latest=rows.find(item=>item.scope_type==='platform_defaults'&&item.status==='approved');if(latest){const value=latest.proposed;settings.daily=Number(value.daily_transfer_cap??settings.daily);settings.ceiling=Number(value.wallet_ceiling??settings.ceiling);settings.safety=Number(value.safety_balance??settings.safety);settings.headroom=Number(value.safety_headroom??settings.headroom);settings.stale=Number(value.balance_stale_seconds??1800)/60;settings.countdown=Number(value.default_deposit_countdown_seconds??600)/60;settings.late=Number(value.default_deposit_late_grace_seconds??1800)/60;settings.factor=Number(value.capacity_safety_factor??.7)*100}}catch(error){ElMessage.error(error instanceof Error?error.message:'Could not load settings')}finally{loading.value=false}}
onMounted(load)
function open(next:typeof action.value,id=''){if(platform.demoMode){ElMessage.success('Demo action simulated.');return}action.value=next;selected.value=id;password.value='';reason.value='';dialog.value=true}
async function submit(){if(reason.value.trim().length<10||!password.value){ElMessage.warning('Enter your password and an audited reason of at least 10 characters.');return}loading.value=true;try{const token=await passwordReauthenticate(password.value);if(action.value==='draft'){await sensitiveApi('/admin/configuration/changes',token,{method:'POST',body:JSON.stringify({scope_type:'platform_defaults',scope_id:'platform',reason:reason.value,proposed:{daily_transfer_cap:settings.daily.toFixed(2),wallet_ceiling:settings.ceiling.toFixed(2),safety_balance:settings.safety.toFixed(2),safety_headroom:settings.headroom.toFixed(2),balance_stale_seconds:settings.stale*60,capacity_safety_factor:settings.factor/100,default_deposit_countdown_seconds:settings.countdown*60,default_deposit_late_grace_seconds:settings.late*60}})})}else if(action.value==='telegram'){const enabled:string[]=[];if(telegram.offline)enabled.push('device_offline');if(telegram.unknown)enabled.push('unknown_payout');if(telegram.balance)enabled.push('stale_balance');if(telegram.webhook)enabled.push('webhook_backlog');await sensitiveApi('/admin/alerts/configuration',token,{method:'POST',body:JSON.stringify({chat_id:telegram.chat,enabled_types:enabled,reason:reason.value})})}else await sensitiveApi(`/admin/configuration/changes/${selected.value}/${action.value}`,token,{method:'POST',body:JSON.stringify({reason:reason.value})});dialog.value=false;ElMessage.success(action.value==='draft'?'Draft submitted for approval':'Audited setting action completed');await load()}catch(error){ElMessage.error(error instanceof Error?error.message:'Setting action failed')}finally{loading.value=false}}
async function testAlert(){try{await api('/admin/alerts/test',{method:'POST',body:JSON.stringify({reason:'Operator requested Telegram routing test'})});ElMessage.success('Test alert queued')}catch(error){ElMessage.error(error instanceof Error?error.message:'Test failed')}}
</script>

<template><div class="page"><div class="page-heading"><div><p class="eyebrow">Platform policy</p><h1>Settings & alerts</h1><span class="muted">Versioned configuration with explicit platform approval and audit history.</span></div><el-button type="primary" :loading="loading" @click="open('draft')">Submit policy draft</el-button></div>
<div class="settings-grid"><nav class="panel"><button v-for="tab in [['limits','Limits & liquidity'],['alerts','Telegram alerts'],['approvals','Pending approvals'] ]" :key="tab[0]" :class="{active:active===tab[0]}" @click="active=tab[0]">{{tab[1]}}</button></nav>
<section v-if="active==='limits'" class="panel settings-card"><div class="panel-head"><div><h2>Default fleet policy</h2><span class="muted small">Active values change only after an approved version.</span></div><el-tag type="warning">Approval required</el-tag></div><div class="panel-body form-grid"><el-form-item label="Daily transfer cap per SIM (ETB)"><el-input-number v-model="settings.daily" :step="5000" :min="1"/></el-form-item><el-form-item label="Wallet ceiling (ETB)"><el-input-number v-model="settings.ceiling" :step="5000" :min="1"/></el-form-item><el-form-item label="Minimum safety balance (ETB)"><el-input-number v-model="settings.safety" :step="500" :min="0"/></el-form-item><el-form-item label="Deposit headroom buffer (ETB)"><el-input-number v-model="settings.headroom" :step="500" :min="0"/></el-form-item><el-form-item label="Balance stale after (minutes)"><el-input-number v-model="settings.stale" :min="5" :max="180"/></el-form-item><el-form-item label="Capacity safety factor (%)"><el-input-number v-model="settings.factor" :min="10" :max="95"/></el-form-item><el-form-item label="Default deposit countdown (minutes)"><el-input-number v-model="settings.countdown" :min="1" :max="60"/></el-form-item><el-form-item label="Default late grace (minutes)"><el-input-number v-model="settings.late" :min="0" :max="120"/></el-form-item><div class="info"><b>Financial day</b><span>Africa/Addis_Ababa · local midnight reset</span></div><div class="info"><b>Policy source</b><span>Approved version in PostgreSQL</span></div></div></section>
<section v-else-if="active==='alerts'" class="panel settings-card"><div class="panel-head"><div><h2>Telegram alert routing</h2><span class="muted small">The bot token remains in the secret store; only routing is persisted here.</span></div><el-button type="primary" @click="open('telegram')">Save routing</el-button></div><div class="panel-body"><el-form label-position="top"><el-form-item label="Chat ID / destination"><el-input v-model="telegram.chat" placeholder="-1001234567890"/></el-form-item><div class="switches"><label><span><b>Device offline</b><small>Fleet heartbeat failures</small></span><el-switch v-model="telegram.offline"/></label><label><span><b>Unknown payout</b><small>Immediate critical escalation</small></span><el-switch v-model="telegram.unknown"/></label><label><span><b>Stale balance</b><small>Approved stale-age threshold</small></span><el-switch v-model="telegram.balance"/></label><label><span><b>Webhook backlog</b><small>Delivery queue pressure</small></span><el-switch v-model="telegram.webhook"/></label></div><el-button @click="testAlert">Queue test alert</el-button></el-form></div></section>
<section v-else class="panel settings-card"><div class="panel-head"><div><h2>Configuration approvals</h2><span class="muted small">{{pending.length}} awaiting review</span></div><el-button :loading="loading" @click="load">Refresh</el-button></div><el-table :data="changes"><el-table-column prop="version" label="Version" width="90"/><el-table-column prop="scope_type" label="Scope"/><el-table-column prop="proposed_by" label="Proposed by"/><el-table-column prop="status" label="Status" width="110"/><el-table-column label="Created" width="170"><template #default="s">{{new Date(s.row.created_at).toLocaleString()}}</template></el-table-column><el-table-column label="Actions" width="185"><template #default="s"><template v-if="s.row.status==='pending'"><el-button size="small" type="success" @click="open('approve',s.row.id)">Approve</el-button><el-button size="small" type="danger" plain @click="open('reject',s.row.id)">Reject</el-button></template></template></el-table-column></el-table></section></div>
<el-dialog v-model="dialog" :title="action==='draft'?'Submit configuration draft':action==='telegram'?'Update Telegram routing':action==='approve'?'Approve configuration':'Reject configuration'" width="min(520px,94vw)"><el-alert title="This action is audited and consumes a one-time password reauthentication token." type="warning" :closable="false" show-icon/><el-form label-position="top" style="margin-top:16px"><el-form-item label="Audited reason"><el-input v-model="reason" type="textarea" :rows="3"/></el-form-item><el-form-item label="Your password"><el-input v-model="password" type="password" show-password autocomplete="current-password"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">Cancel</el-button><el-button type="primary" :loading="loading" @click="submit">Confirm</el-button></template></el-dialog></div></template>

<style scoped>.settings-grid{display:grid;grid-template-columns:230px minmax(0,900px);gap:18px;align-items:start}.settings-grid nav{padding:10px}.settings-grid nav button{display:block;width:100%;border:0;background:transparent;text-align:left;padding:12px;border-radius:8px;color:#606a80;cursor:pointer}.settings-grid nav button.active{background:var(--primary-soft);color:var(--primary);font-weight:700}.settings-card{min-height:430px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px 20px}.form-grid :deep(.el-input-number){width:100%}.info{padding:13px;background:#f6f7fa;border-radius:9px}.info b,.info span{display:block}.info b{font-size:11px}.info span{font-size:10px;color:var(--muted);margin-top:4px}.switches{margin-bottom:18px}.switches label{display:flex;align-items:center;justify-content:space-between;padding:14px 0;border-bottom:1px solid var(--line)}.switches b,.switches small{display:block}.switches b{font-size:12px}.switches small{font-size:10px;color:var(--muted);margin-top:3px}@media(max-width:800px){.settings-grid{grid-template-columns:1fr}.settings-grid nav{display:flex;overflow:auto}.settings-grid nav button{white-space:nowrap}.form-grid{grid-template-columns:1fr}}</style>
