import {computed,ref} from 'vue'
import {defineStore} from 'pinia'
import {devices as mockDevices} from '../data/mock'
import {adminDemoMode,adminSession,api,passwordReauthenticate,sensitiveApi} from '../api/client'
import type {Device,Health,OperationRecord} from '../types'

export type AdminSupportStatus='open'|'investigating'|'awaiting_merchant'|'resolved'|'closed'
export interface AdminSupportMessage{id:string;body:string;evidence_reference:string|null;proposed_match:{kind:string;reference:string;explanation?:string}|null;author:{type:string;id:string|null;display_name:string};created_at:string}
export interface AdminSupportCase{id:string;merchant?:{id:string;slug:string;name:string};environment:'test'|'live';category:string;subject:string;reference:string|null;status:AdminSupportStatus;workflow_note:string|null;created_by:{id:string;display_name:string}|null;assigned_to:{id:string;display_name:string}|null;message_count:number;messages?:AdminSupportMessage[];created_at:string;updated_at:string;resolved_at:string|null;financial_resolution_performed:false}

export const usePlatformStore=defineStore('platform',()=>{
  const devices=ref<Device[]>(adminDemoMode?mockDevices:[])
  const authenticated=ref(adminDemoMode||Boolean(adminSession.get()))
  const identity=ref<{id:string;email:string|null;display_name:string;role:string;auth_kind:string}|null>(adminDemoMode?{id:'demo',email:'admin@example.test',display_name:'Selam A.',role:'admin',auth_kind:'demo'}:null)
  const authError=ref('')
  const dashboard=ref<Record<string,unknown>|null>(null)
  const operations=ref<Record<'jobs'|'deposits'|'withdrawals',OperationRecord[]>>({jobs:[],deposits:[],withdrawals:[]})
  const merchants=ref<Array<{id:string;slug:string;name:string;status:string;user_count:number;available:string;fleet_policies:Array<{group_id:string;group:string;dedicated:boolean;priority:number}>}>>([])
  const auditRows=ref<Array<Record<string,unknown>>>([])
  const reconciliationCases=ref<Array<Record<string,unknown>>>([])
  const supportCases=ref<AdminSupportCase[]>([])
  const alerts=ref<Array<{id:string;type:string;message:string;metadata:Record<string,unknown>;created_at:string}>>([])
  const refreshing=ref(false)
  const refreshedAt=ref(new Date())
  const totalSpendable=computed(()=>devices.value.flatMap(device=>device.sims).reduce((total,sim)=>total+sim.balance,0))
  const qualifiedPhones=computed(()=>devices.value.filter(device=>device.status==='online').length)
  function health(status:string):Health{return status==='online'||status==='active'?'healthy':status==='degraded'||status==='payout_stale'?'warning':status==='quarantined'?'quarantined':'offline'}
  function age(date:string|null){if(!date)return 999;return Math.max(0,Math.round((Date.now()-new Date(date).valueOf())/60000))}
  function mapFleet(locations:any[]):Device[]{return locations.flatMap(location=>location.groups.flatMap((group:any)=>group.devices.map((device:any)=>({id:device.id,status:device.status,name:device.name,model:device.model??'Unknown',location:location.name,group:group.name,health:health(device.status),lastSeen:device.last_heartbeat_at?new Date(device.last_heartbeat_at).toLocaleString():'Never',battery:device.battery_percent??0,temperature:Number(device.temperature_celsius??0),appVersion:device.agent_version??'—',profileVersion:device.ussd_profile_version??'—',sims:device.sims.map((sim:any)=>({id:sim.id,slot:(sim.slot+1) as 1|2,phone:sim.phone_number_masked,accountName:sim.account_name,balance:Number(sim.main_balance),balanceAge:age(sim.last_balance_at),dailyUsed:Number(sim.sent_today),dailyLimit:Number(group.daily_limit),health:health(sim.status)}))}))))}
  async function login(email:string,password:string){authError.value='';refreshing.value=true;try{const result=await api<{session_token:string;staff:{id:string;email:string;display_name:string;role:string}}>('/admin/auth/login',{method:'POST',body:JSON.stringify({email,password})});adminSession.set(result.session_token);authenticated.value=true;identity.value={...result.staff,auth_kind:'session'};await refresh()}catch(error){authError.value=error instanceof Error?error.message:'Sign in failed';throw error}finally{refreshing.value=false}}
  async function restore(){if(adminDemoMode)return;if(!adminSession.get()){authenticated.value=false;return}try{identity.value=await api('/admin/auth/me');authenticated.value=true;await refresh()}catch{adminSession.clear();authenticated.value=false;identity.value=null}}
  async function logout(){try{if(!adminDemoMode)await api('/admin/auth/logout',{method:'POST'})}finally{adminSession.clear();authenticated.value=adminDemoMode;if(!adminDemoMode)identity.value=null}}
  async function refresh(){refreshing.value=true;try{if(adminDemoMode){await new Promise(resolve=>setTimeout(resolve,250))}else{const [dashboardResult,fleet,alertResult]=await Promise.all([api<Record<string,unknown>>('/admin/dashboard'),api<any[]>('/admin/fleet'),api<{alerts:Array<{id:string;type:string;message:string;metadata:Record<string,unknown>;created_at:string}>}>('/admin/alerts')]);dashboard.value=dashboardResult;devices.value=mapFleet(fleet);alerts.value=alertResult.alerts}refreshedAt.value=new Date()}finally{refreshing.value=false}}
  async function loadOperations(kind:'jobs'|'deposits'|'withdrawals'){if(adminDemoMode)return;const rows=await api<Array<any>>(`/admin/operations/${kind}`);operations.value[kind]=rows.map(row=>({id:row.id,merchant:row.merchant,reference:row.reference,customer:row.customer,amount:Number(row.amount),status:row.status,p2pStatus:row.p2p_status,age:new Date(row.created_at).toLocaleString(),device:row.device??undefined,log:row.log??[],canExecuteNow:Boolean(row.can_execute_now),canRetry:Boolean(row.can_retry)}))}
  async function executeDeviceJobNow(jobId:string){const result=await api<any>(`/admin/device-jobs/${jobId}/execute-now`,{method:'POST'});await loadOperations('jobs');return result}
  async function retryDeviceJob(jobId:string){const result=await api<any>(`/admin/device-jobs/${jobId}/retry`,{method:'POST'});await loadOperations('jobs');return result}
  async function loadMerchants(){if(adminDemoMode)return;merchants.value=await api('/admin/merchants')}
  async function createMerchant(input:{slug:string;name:string;owner_email:string;initial_test_balance?:string},password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi<{id:string;slug:string;name:string;owner_invitation:{email:string;token:string;expires_at:string};keys:Array<{environment:string;secret_key:string}>}>('/admin/merchants',token,{method:'POST',body:JSON.stringify(input)});await loadMerchants();return result}
  async function loadAudit(){if(adminDemoMode)return;auditRows.value=await api('/admin/audit')}
  async function loadCases(){if(adminDemoMode)return;reconciliationCases.value=await api('/admin/reconciliation/cases')}
  async function loadSupportCases(){if(adminDemoMode)return;supportCases.value=await api('/admin/support/cases?limit=200')}
  async function loadSupportCase(id:string){if(adminDemoMode)return supportCases.value.find(item=>item.id===id)??null;const detail=await api<AdminSupportCase>(`/admin/support/cases/${id}`);const index=supportCases.value.findIndex(item=>item.id===id);if(index>=0)supportCases.value[index]=detail;else supportCases.value.unshift(detail);return detail}
  async function addSupportMessage(id:string,input:{message:string;evidence_reference?:string;proposed_match?:{kind:string;reference:string;explanation?:string}}){const detail=await api<AdminSupportCase>(`/admin/support/cases/${id}/messages`,{method:'POST',body:JSON.stringify(input)});const index=supportCases.value.findIndex(item=>item.id===id);if(index>=0)supportCases.value[index]=detail;return detail}
  async function changeSupportStatus(id:string,status:AdminSupportStatus,reason:string){const detail=await api<AdminSupportCase>(`/admin/support/cases/${id}/status`,{method:'POST',body:JSON.stringify({status,reason})});const index=supportCases.value.findIndex(item=>item.id===id);if(index>=0)supportCases.value[index]=detail;return detail}
  async function fleetTree(){return api<Array<any>>('/admin/fleet')}
  async function createLocation(input:{code:string;name:string}){return api<any>('/admin/fleet/locations',{method:'POST',body:JSON.stringify(input)})}
  async function createGroup(input:{location_id:string;code:string;name:string}){return api<any>('/admin/fleet/groups',{method:'POST',body:JSON.stringify(input)})}
  async function upsertMerchantGroupPolicy(input:{group_id:string;merchant_id:string;dedicated:boolean;priority:number;reason:string},password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi<any>(`/admin/fleet/groups/${input.group_id}/merchant-policies/${input.merchant_id}`,token,{method:'PUT',body:JSON.stringify({dedicated:input.dedicated,priority:input.priority,reason:input.reason})});await loadMerchants();return result}
  async function removeMerchantGroupPolicy(input:{group_id:string;merchant_id:string;reason:string},password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi<any>(`/admin/fleet/groups/${input.group_id}/merchant-policies/${input.merchant_id}`,token,{method:'DELETE',body:JSON.stringify({reason:input.reason})});await loadMerchants();return result}
  async function createDevice(input:{group_id:string;name:string;model?:string;sims:Array<{slot:number;iccid:string;phone_number:string;account_name:string}>}){return api<any>('/admin/fleet/devices',{method:'POST',body:JSON.stringify(input)})}
  async function getDevice(deviceId:string){return api<any>(`/admin/fleet/devices/${deviceId}`)}
  async function setDeviceOnline(deviceId:string,online:boolean){const result=await api<any>(`/admin/fleet/devices/${deviceId}/online`,{method:'POST',body:JSON.stringify({online})});await refresh();return result}
  async function deleteDevice(deviceId:string,reason:string,password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi<any>(`/admin/fleet/devices/${deviceId}`,token,{method:'DELETE',body:JSON.stringify({reason})});await refresh();return result}
  async function queueBalance(simId:string){const result=await api<any>(`/admin/fleet/sims/${simId}/balance-query`,{method:'POST'});await refresh();return result}
  async function quarantineDevice(deviceId:string,reason:string,password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi<any>(`/admin/fleet/devices/${deviceId}/quarantine`,token,{method:'POST',body:JSON.stringify({reason})});await refresh();return result}
  async function recoverDevice(deviceId:string,input:{reason:string;replacement_hardware:boolean;sims:Array<{slot:number;iccid:string;phone_number:string;account_name:string}>},password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi<any>(`/admin/fleet/devices/${deviceId}/recover`,token,{method:'POST',body:JSON.stringify(input)});await refresh();return result}
  async function retireDevice(deviceId:string,reason:string,password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi<any>(`/admin/fleet/devices/${deviceId}/retire`,token,{method:'POST',body:JSON.stringify({reason})});await refresh();return result}
  async function regenerateActivationCode(deviceId:string){return api<any>(`/admin/fleet/devices/${deviceId}/activation-code`,{method:'POST'})}
  async function getQualification(deviceId:string){return api<any>(`/admin/fleet/devices/${deviceId}/qualification`)}
  async function startQualification(deviceId:string){return api<any>(`/admin/fleet/devices/${deviceId}/qualification-runs`,{method:'POST'})}
  async function recordQualificationCheck(runId:string,checkId:string,input:{status:'passed'|'failed';evidence_reference:string;notes?:string}){return api<any>(`/admin/fleet/qualification-runs/${runId}/checks/${checkId}`,{method:'POST',body:JSON.stringify(input)})}
  async function decideQualification(runId:string,decision:'approve'|'reject',reason:string,password:string){const token=await passwordReauthenticate(password);return sensitiveApi<any>(`/admin/fleet/qualification-runs/${runId}/${decision}`,token,{method:'POST',body:JSON.stringify({reason})})}
  async function cancelTransfer(transferId:string,reason:string,password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi(`/admin/transfers/${transferId}/cancel`,token,{method:'POST',body:JSON.stringify({reason})});await loadCases();return result}
  async function approveNameRetry(transferId:string,reason:string,password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi(`/admin/transfers/${transferId}/retry-name-approved`,token,{method:'POST',body:JSON.stringify({reason})});await loadCases();return result}
  async function resolveTransfer(transferId:string,input:Record<string,unknown>,password:string){const token=await passwordReauthenticate(password);const result=await sensitiveApi(`/admin/transfers/${transferId}/resolve`,token,{method:'POST',body:JSON.stringify(input)});await loadCases();return result}
  async function createTestDeposit(input:{merchant_id:string;amount:string;first_name:string;last_name?:string;phone_number:string}){if(adminDemoMode)throw new Error('Connect the admin to the API to run live payment tests');return api<any>('/admin/test/deposits',{method:'POST',body:JSON.stringify(input)})}
  async function createTestWithdrawal(input:{merchant_id:string;amount:string;account_number:string;expected_name:string}){if(adminDemoMode)throw new Error('Connect the admin to the API to run live payment tests');return api<any>('/admin/test/withdrawals',{method:'POST',body:JSON.stringify(input)})}
  return{devices,authenticated,identity,authError,dashboard,operations,merchants,auditRows,reconciliationCases,supportCases,alerts,demoMode:adminDemoMode,refreshing,refreshedAt,totalSpendable,qualifiedPhones,login,restore,logout,refresh,loadOperations,executeDeviceJobNow,retryDeviceJob,loadMerchants,createMerchant,loadAudit,loadCases,loadSupportCases,loadSupportCase,addSupportMessage,changeSupportStatus,fleetTree,createLocation,createGroup,upsertMerchantGroupPolicy,removeMerchantGroupPolicy,createDevice,getDevice,setDeviceOnline,deleteDevice,queueBalance,quarantineDevice,recoverDevice,retireDevice,regenerateActivationCode,getQualification,startQualification,recordQualificationCheck,decideQualification,cancelTransfer,approveNameRetry,resolveTransfer,createTestDeposit,createTestWithdrawal}
})
