<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue';import {CirclePlus,CopyDocument,RefreshRight} from '@element-plus/icons-vue';import {ElMessage,ElMessageBox} from 'element-plus';import {useMerchantStore} from '../stores/merchant';
const props=defineProps<{tab:'keys'|'webhooks'}>();const store=useMerchantStore();const live=ref(store.environment==='live');const keyDialog=ref(false);const webhookDialog=ref(false);const label=ref('Server integration');const webhookUrl=ref('');const revealedSecret=ref('');const title=computed(()=>props.tab==='keys'?'API keys':'Webhooks');const deliveries=computed(()=>store.webhooks.flatMap(endpoint=>endpoint.deliveries.map(item=>({...item,endpoint:endpoint.url}))));
watch(live,async value=>{await store.switchEnvironment(value?'live':'test');await store.loadDeveloper()});watch(()=>props.tab,()=>{revealedSecret.value=''});onMounted(()=>store.loadDeveloper());function copy(value:string){navigator.clipboard?.writeText(value);ElMessage.success('Copied')}
async function createKey(){const result=await store.createApiKey(label.value);revealedSecret.value=result.secret_key;keyDialog.value=false}
async function revoke(id:string){await store.revokeApiKey(id);ElMessage.success('Key revoked')}
async function createWebhook(){const result=await store.createWebhook(webhookUrl.value);revealedSecret.value=result.secret;webhookDialog.value=false}
async function toggleWebhook(id:string,enabled:boolean){if(!enabled)await ElMessageBox.confirm('Pending deliveries will be cancelled and no new events will be sent until this endpoint is enabled again.','Disable webhook',{type:'warning'});await store.setWebhookEnabled(id,enabled);ElMessage.success(enabled?'Webhook enabled':'Webhook disabled')}
async function rotateWebhook(id:string){await ElMessageBox.confirm('The previous signing secret will stop being used. Update your receiver immediately after copying the new secret.','Rotate webhook secret',{type:'warning'});const result=await store.rotateWebhookSecret(id);revealedSecret.value=result.secret;ElMessage.success('Webhook secret rotated')}
</script>
<template><div class="page"><div class="page-heading"><div><p class="eyebrow">Developer integration</p><h1>{{title}}</h1><span class="muted">{{tab==='keys'?'Authenticate server requests in test and live environments.':'Monitor signed, at-least-once event delivery.'}}</span></div><el-button type="primary" :icon="CirclePlus" @click="tab==='keys'?keyDialog=true:webhookDialog=true">{{tab==='keys'?'Create key':'Add endpoint'}}</el-button></div>
<div class="environment"><span>Environment</span><el-radio-group v-model="live"><el-radio-button :value="false">Test</el-radio-button><el-radio-button :value="true">Live</el-radio-button></el-radio-group><el-alert v-if="live" title="Live requests move real money." type="warning" :closable="false" show-icon/></div>
<el-alert v-if="revealedSecret" title="Copy this secret now. It will not be shown again." type="success" :closable="false" show-icon class="once"><div class="secret"><code>{{revealedSecret}}</code><el-button :icon="CopyDocument" @click="copy(revealedSecret)">Copy</el-button></div></el-alert>
<template v-if="tab==='keys'"><section v-for="key in store.apiKeys" :key="key.id" class="panel key-card"><div class="panel-head"><div><h2>{{key.label}}</h2><span class="muted small">{{key.prefix}} · secret values are never loaded again</span></div><el-tag :type="key.active?'success':'info'">{{key.active?'Active':'Revoked'}}</el-tag></div><div class="panel-body"><div class="secret"><code>{{key.prefix}}.••••••••••••••••••••••••</code><el-button :icon="CopyDocument" @click="copy(key.prefix)">Copy prefix</el-button></div><div class="key-meta"><span>Created <b>{{new Date(key.created_at).toLocaleDateString()}}</b></span><span>Last used <b>{{key.last_used_at?new Date(key.last_used_at).toLocaleString():'Never'}}</b></span><span>Environment <b>{{key.environment}}</b></span></div><el-button v-if="key.active" type="danger" plain :icon="RefreshRight" @click="revoke(key.id)">Revoke key</el-button></div></section><el-empty v-if="!store.apiKeys.length" description="No API keys in this environment"/></template>
<template v-else><section v-for="endpoint in store.webhooks" :key="endpoint.id" class="panel endpoint"><div class="panel-head"><div><h2>Webhook endpoint</h2><span class="muted small">{{endpoint.url}}</span></div><div class="endpoint-actions"><span :class="['status',endpoint.enabled?'status-success':'status-failed']">{{endpoint.enabled?'Enabled':'Disabled'}}</span><el-button size="small" @click="rotateWebhook(endpoint.id)">Rotate secret</el-button><el-button size="small" :type="endpoint.enabled?'danger':'success'" plain @click="toggleWebhook(endpoint.id,!endpoint.enabled)">{{endpoint.enabled?'Disable':'Enable'}}</el-button></div></div><div class="panel-body delivery"><div><span>Deliveries shown</span><strong>{{endpoint.deliveries.length}}</strong><small>Most recent 100</small></div><div><span>Delivered</span><strong>{{endpoint.deliveries.filter(x=>x.status==='delivered').length}}</strong><small>At least once</small></div><div><span>Pending / dead</span><strong>{{endpoint.deliveries.filter(x=>x.status!=='delivered').length}}</strong><small>Replay is audited</small></div></div></section><section class="panel"><div class="panel-head"><div><h2>Recent deliveries</h2><span class="muted small">Events can be duplicated or arrive out of order</span></div></div><el-table :data="deliveries"><el-table-column prop="event_type" label="Event" min-width="180"/><el-table-column prop="event_id" label="Event ID" min-width="140"/><el-table-column label="Response" width="110"><template #default="s"><el-tag :type="s.row.response_code&&s.row.response_code<300?'success':'danger'">{{s.row.response_code?`HTTP ${s.row.response_code}`:s.row.status}}</el-tag></template></el-table-column><el-table-column prop="attempt" label="Attempt" width="90"/><el-table-column label="Time" width="160"><template #default="s">{{new Date(s.row.created_at).toLocaleString()}}</template></el-table-column><el-table-column width="80"><template #default="s"><el-button link type="primary" :disabled="s.row.status==='delivered'" @click="store.replayWebhook(s.row.id)">Replay</el-button></template></el-table-column></el-table></section></template>
<el-dialog v-model="keyDialog" title="Create API key" width="min(480px,92vw)"><el-form label-position="top"><el-form-item label="Label"><el-input v-model="label" maxlength="100"/></el-form-item></el-form><el-alert title="The secret is displayed once after creation." type="warning" :closable="false" show-icon/><template #footer><el-button @click="keyDialog=false">Cancel</el-button><el-button type="primary" @click="createKey">Create key</el-button></template></el-dialog>
<el-dialog v-model="webhookDialog" title="Add webhook endpoint" width="min(520px,92vw)"><el-form label-position="top"><el-form-item label="HTTPS URL"><el-input v-model="webhookUrl" placeholder="https://merchant.example/webhooks/orbitpay"/></el-form-item></el-form><el-alert title="The signing secret is displayed once after creation." type="warning" :closable="false" show-icon/><template #footer><el-button @click="webhookDialog=false">Cancel</el-button><el-button type="primary" @click="createWebhook">Add endpoint</el-button></template></el-dialog></div></template>
<style scoped>.environment{display:flex;align-items:center;gap:12px;margin-bottom:17px}.environment>span{font-size:10px;font-weight:700;color:var(--muted)}.environment .el-alert{margin-left:auto;max-width:300px}.once{margin-bottom:17px}.key-card,.endpoint{margin-bottom:17px}.endpoint-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.secret{display:flex;gap:8px;align-items:center;padding:10px;background:#f6f7fa;border-radius:10px}.secret code{flex:1;overflow:auto;font-size:12px;color:#343d52;white-space:nowrap}.key-meta{display:flex;gap:30px;padding:16px 0;font-size:10px;color:var(--muted)}.key-meta b{color:var(--ink);margin-left:4px}.delivery{display:grid;grid-template-columns:repeat(3,1fr);align-items:center}.delivery>div{border-right:1px solid var(--line)}.delivery>div:last-child{border:0}.delivery span,.delivery strong,.delivery small{display:block}.delivery span{font-size:9px;text-transform:uppercase;color:var(--muted)}.delivery strong{font:800 20px 'Manrope';margin:5px 0}.delivery small{font-size:9px;color:var(--muted)}@media(max-width:700px){.environment{flex-wrap:wrap}.environment .el-alert{margin-left:0;max-width:none}.secret{flex-wrap:wrap}.secret code{width:100%;flex-basis:100%}.key-meta{flex-direction:column;gap:7px}.delivery{grid-template-columns:1fr 1fr;gap:18px}.delivery>div{border:0}}</style>
