export type DepositStatus='awaiting_payment'|'late_grace'|'matching'|'manual_review'|'success'|'expired'|'failed'
export interface DepositIntent{token:string;merchantName:string;merchantLogo:string;reference:string;amount:string;creditedAmount:string|null;currency:'ETB';receiverPhone:string;receiverName:string;expiresAt:string;lateGraceEndsAt:string;countdownSeconds:number;lateGraceSeconds:number;status:DepositStatus;returnUrl?:string}
export type WithdrawalStatus='accepted'|'queued'|'device_assigned'|'device_started'|'committed'|'provider_pending'|'success'|'failed'|'unknown'|'manual_review'|'cancelled'
export interface Withdrawal{reference:string;merchantName:string;amount:string;destination:string;receiverName:string;status:WithdrawalStatus;etaSeconds:number;createdAt:string;message?:string}
interface HostedDepositResponse{tx_ref:string;amount:string;credited_amount:string|null;currency:'ETB';p2p_status:DepositStatus;assigned_phone_number:string;receiver_name:string;expires_at:string;late_grace_ends_at:string;countdown_seconds:number;late_grace_seconds:number;return_url?:string;merchant_name?:string}
interface HostedWithdrawalResponse{reference:string;amount:string;p2p_status:WithdrawalStatus;account_number_masked:string;expected_name:string;eta_seconds:number;created_at:string;merchant_name?:string;message?:string}
const base=import.meta.env.VITE_API_BASE_URL||'/v1';
async function request<T>(path:string):Promise<T>{const response=await fetch(`${base}${path}`);if(!response.ok)throw new Error(`Request failed (${response.status})`);const body=await response.json();return (body.data??body) as T}
export const mockDeposit=(token:string):DepositIntent=>({token,merchantName:'AsterBet',merchantLogo:'AB',reference:'AB-249155',amount:'2000.00',creditedAmount:null,currency:'ETB',receiverPhone:'099 284 4697',receiverName:'Abayine Fucha',expiresAt:new Date(Date.now()+10*60_000).toISOString(),lateGraceEndsAt:new Date(Date.now()+40*60_000).toISOString(),countdownSeconds:600,lateGraceSeconds:1800,status:'awaiting_payment',returnUrl:'#'})
export const mockWithdrawal=(reference:string):Withdrawal=>({reference,merchantName:'AsterBet',amount:'1500.00',destination:'092 ••• 4697',receiverName:'Abayine Fucha',status:'queued',etaSeconds:42,createdAt:new Date().toISOString()})
export function mapHostedDeposit(data:HostedDepositResponse,token:string):DepositIntent{return{token,merchantName:data.merchant_name||'Merchant',merchantLogo:(data.merchant_name||'M').slice(0,2).toUpperCase(),reference:data.tx_ref,amount:data.amount,creditedAmount:data.credited_amount,currency:data.currency,receiverPhone:data.assigned_phone_number,receiverName:data.receiver_name,expiresAt:data.expires_at,lateGraceEndsAt:data.late_grace_ends_at,countdownSeconds:data.countdown_seconds,lateGraceSeconds:data.late_grace_seconds,status:data.p2p_status,returnUrl:data.return_url}}
export async function getDeposit(txRef:string,token:string):Promise<DepositIntent>{if(import.meta.env.VITE_USE_MOCKS==='true'||txRef==='demo')return mockDeposit(token);const data=await request<HostedDepositResponse>(`/checkout/${encodeURIComponent(txRef)}?token=${encodeURIComponent(token)}`);return mapHostedDeposit(data,token)}
function mapHostedWithdrawal(data:HostedWithdrawalResponse):Withdrawal{return{reference:data.reference,merchantName:data.merchant_name||'Merchant',amount:data.amount,destination:data.account_number_masked,receiverName:data.expected_name,status:data.p2p_status,etaSeconds:data.eta_seconds,createdAt:data.created_at,message:data.message}}
export async function getWithdrawal(reference:string,token?:string):Promise<Withdrawal>{if(import.meta.env.VITE_USE_MOCKS==='true'||reference==='demo')return mockWithdrawal(reference);return mapHostedWithdrawal(await request<HostedWithdrawalResponse>(`/hosted/transfers/${encodeURIComponent(reference)}?token=${encodeURIComponent(token||'')}`))}
export function withdrawalEventUrl(reference:string,token:string):string{return`${base}/hosted/transfers/${encodeURIComponent(reference)}/events?token=${encodeURIComponent(token)}`}
